# Project Brazilian e-commerce by Olist

## Modeling Schema

<img src=..\docs\assets\data_schema.png width="900">

Source: https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce

## Data Dictionary

| Features | Description | Tables |
| :--- | :--- | :--- |
| customer_city | customer city name | customers |
| customer_id | key to the orders dataset. Each order has a unique customer_id. | customers, orders |
| customer_state | customer state | customers |
| customer_unique_id | unique identifier of a customer. | customers |
| customer_zip_code_prefix | first five digits of customer zip code | customers |
| freight_value | item freight value item (if an order has more than one item the freight value is splitted between items) | items |
| geolocation_city | city name | geolocation |
| geolocation_lat | latitude | geolocation |
| geolocation_lng | longitude | geolocation |
| geolocation_state | state | geolocation |
| geolocation_zip_code_prefix | first 5 digits of zip code | geolocation |
| order_approved_at | Shows the payment approval timestamp. | orders |
| order_delivered_carrier_date | Shows the order posting timestamp. When it was handled to the logistic partner. | orders |
| order_delivered_customer_date | Shows the actual order delivery date to the customer. | orders |
| order_estimated_delivery_date | Shows the estimated delivery date that was informed to customer at the purchase moment. | orders |
| order_id | order unique identifier | items, payments, reviews, orders |
| order_item_id | sequential number identifying number of items included in the same order | items |
| order_purchase_timestamp | Shows the purchase timestamp. | orders |
| order_status | Reference to the order status (delivered, shipped, etc). | orders |
| payment_installments | number of installments chosen by the customer. | payments |
| payment_sequential | a customer may pay an order with more than one payment method. If he does so, a sequence will be created to | payments |
| payment_type | method of payment chosen by the customer. | payments |
| payment_value | transaction value. | payments |
| price | item price | items |
| product_category_name | root category of product, in Portuguese. | products |
| > product_description_lenght | number of characters extracted from the product description. | products |
| product_height_cm | product height measured in centimeters. | products |
| product_id | product unique identifier | items, products |
| product_length_cm | product length measured in centimeters. | products |
| > product_name_lenght | number of characters extracted from the product name. | products |
| product_photos_qty | number of product published photos. | products |
| product_weight_g | product weight measured in grams. | products |
| product_width_cm | product width measured in centimeters. | products |
| review_answer_timestamp | Shows satisfaction survey answer timestamp. | reviews |
| review_comment_message | Comment message from the review left by the customer, in Portuguese. | reviews |
| review_comment_title | Comment title from the review left by the customer, in Portuguese. | reviews |
| review_creation_date | Shows the date in which the satisfaction survey was sent to the customer. | reviews |
| review_id | unique review identifier | reviews |
| review_score | Note ranging from 1 to 5 given by the customer on a satisfaction survey. | reviews |
| seller_city | seller city name | sellers |
| seller_id | seller unique identifier | items, sellers |
| seller_state | seller state | sellers |
| seller_zip_code_prefix | first 5 digits of seller zip code | sellers |
| shipping_limit_date | Shows the seller shipping limit date for handling the order over to the logistic partner. | items |

In [1]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

import pandas as pd
from src.eda_utils import dataframe_summary

## Reading Data

In [2]:
customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")
geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")
order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
order_payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")
products = pd.read_csv("../data/raw/olist_products_dataset.csv")
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

In [3]:
dfs = {
    "customers": customers,
    "geolocation": geolocation,
    "items": order_items,
    "payments": order_payments,
    "reviews": order_reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
}

In [4]:
for name, df in dfs.items():
    print(f'{name.upper()} {df.shape}:')
    display(dataframe_summary(df))

CUSTOMERS (99441, 5):

,feature,dtype,total_null,percent_null,unique,top,freq,mean,std,25%,50%,75%,min,max,skew,kurtosis
3,customer_city,str,0,0.0,4119,sao paulo,15540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,customer_id,str,0,0.0,99441,06b8999e2fba1a1fbc88172c00ba8bc7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,customer_state,str,0,0.0,27,SP,41746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,customer_unique_id,str,0,0.0,96096,8d50f5eadf50201ccdcedfb9e2ac8455,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,customer_zip_code_prefix,int64,0,0.0,14994,22790,142,35137.474583,29797.938996,11347.0,24416.0,58900.0,1003.0,99990.0,0.779025,-0.788204

GEOLOCATION (1000163, 5):

,feature,dtype,total_null,percent_null,unique,top,freq,mean,std,25%,50%,75%,min,max,skew,kurtosis
3,geolocation_city,str,0,0.0,8011,sao paulo,135800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,geolocation_lat,float64,0,0.0,717360,-27.102099,314,-21.176153,5.715866,-23.603546,-22.919377,-19.979620,-36.605374,45.065933,1.565147,2.850097
2,geolocation_lng,float64,0,0.0,717613,-48.629613,314,-46.390541,4.269748,-48.573172,-46.637879,-43.767709,-101.466766,121.105394,-0.102417,4.727051
4,geolocation_state,str,0,0.0,27,SP,404268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,geolocation_zip_code_prefix,int64,0,0.0,19015,24220,1146,36574.166466,30549.335710,11075.000000,26530.000000,63504.000000,1001.000000,99990.000000,0.694494,-0.941226

ITEMS (112650, 7):

,feature,dtype,total_null,percent_null,unique,top,freq,mean,std,25%,50%,75%,min,max,skew,kurtosis
6,freight_value,float64,0,0.0,6999,15.1,3707,19.990320,15.806405,13.08,16.26,21.15,0.00,409.68,5.639870,59.788253
0,order_id,str,0,0.0,98666,8272b63d03f5f79c56e9e4120aec44ef,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,order_item_id,int64,0,0.0,21,1,98666,1.197834,0.705124,1.00,1.00,1.00,1.00,21.00,7.580356,103.857361
5,price,float64,0,0.0,5968,59.9,2481,120.653739,183.633928,39.90,74.99,134.90,0.85,6735.00,7.923208,120.828298
2,product_id,str,0,0.0,32951,aca2eb7d00ea1a7b8ebd4e68314663af,527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,seller_id,str,0,0.0,3095,6560211a19b47992c3666cc44a7e94c0,2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,shipping_limit_date,str,0,0.0,93318,2018-03-01 02:50:48,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

PAYMENTS (103886, 5):

,feature,dtype,total_null,percent_null,unique,top,freq,mean,std,25%,50%,75%,min,max,skew,kurtosis
0,order_id,str,0,0.0,99440,fa65dad1b0e818e3ccc5cb0e39231352,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,payment_installments,int64,0,0.0,24,1,52546,2.853349,2.687051,1.00,1.0,4.0000,0.0,24.00,1.655074,2.550048
1,payment_sequential,int64,0,0.0,29,1,99360,1.092679,0.706584,1.00,1.0,1.0000,1.0,29.00,16.180065,370.593809
2,payment_type,str,0,0.0,5,credit_card,76795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,payment_value,float64,0,0.0,29077,50.0,324,154.100380,217.494064,56.79,100.0,171.8375,0.0,13664.08,9.254010,241.828442

REVIEWS (99224, 7):

,feature,dtype,total_null,percent_null,unique,top,freq,mean,std,25%,50%,75%,min,max,skew,kurtosis
1,order_id,str,0,0.00,98673,c88b1d1b157a9999ce368f218a407141,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,review_answer_timestamp,str,0,0.00,98248,2017-06-15 23:21:05,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,review_comment_message,str,58247,58.70,36159,Muito bom,230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,review_comment_title,str,87656,88.34,4527,Recomendo,423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,review_creation_date,str,0,0.00,636,2017-12-19 00:00:00,463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,review_id,str,0,0.00,98410,c444278834184f72b1484dfe47de7f97,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,review_score,int64,0,0.00,5,5,57328,4.086421,1.347579,4.0,5.0,5.0,1.0,5.0,-1.364386,0.507653

ORDERS (99441, 8):

,feature,dtype,total_null,percent_null,unique,top,freq,mean,std,25%,50%,75%,min,max,skew,kurtosis
1,customer_id,str,0,0.00,99441,9ef432eb6251297304e76186b10a928d,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,order_approved_at,str,160,0.16,90733,2018-02-27 04:31:10,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,order_delivered_carrier_date,str,1783,1.79,81018,2018-05-09 15:48:00,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,order_delivered_customer_date,str,2965,2.98,95664,2018-05-14 20:02:44,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,order_estimated_delivery_date,str,0,0.00,459,2017-12-20 00:00:00,522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,order_id,str,0,0.00,99441,e481f51cbdc54678b7cc49136f2d6af7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,order_purchase_timestamp,str,0,0.00,98875,2018-03-31 15:08:21,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,order_status,str,0,0.00,8,delivered,96478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

PRODUCTS (32951, 9):

,feature,dtype,total_null,percent_null,unique,top,freq,mean,std,25%,50%,75%,min,max,skew,kurtosis
1,product_category_name,str,610,1.85,73,cama_mesa_banho,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,product_description_lenght,float64,610,1.85,2960,404.0,94,771.495285,635.115225,339.0,595.0,972.0,4.0,3992.0,1.962093,4.828923
7,product_height_cm,float64,2,0.01,102,10.0,2548,16.937661,13.637554,8.0,13.0,21.0,2.0,105.0,2.140061,6.678619
0,product_id,str,0,0.00,32951,1e9e8ef04dbcff4541ed26657ea517e5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,product_length_cm,float64,2,0.01,99,16.0,5520,30.815078,16.914458,18.0,25.0,38.0,7.0,105.0,1.750460,3.513618
2,product_name_lenght,float64,610,1.85,66,60.0,2182,48.476949,10.245741,42.0,51.0,57.0,5.0,76.0,-0.903222,0.192563
4,product_photos_qty,float64,610,1.85,19,1.0,16489,2.188986,1.736766,1.0,1.0,3.0,1.0,20.0,2.193409,7.263534
5,product_weight_g,float64,2,0.01,2204,200.0,2084,2276.472488,4282.038731,300.0,700.0,1900.0,0.0,40425.0,3.604860,15.133565
8,product_width_cm,float64,2,0.01,95,11.0,3718,23.196728,12.079047,15.0,20.0,30.0,6.0,118.0,1.670971,4.073126

SELLERS (3095, 4):

,feature,dtype,total_null,percent_null,unique,top,freq,mean,std,25%,50%,75%,min,max,skew,kurtosis
2,seller_city,str,0,0.0,611,sao paulo,694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,seller_id,str,0,0.0,3095,3442f8959a84dea7ee197c632cb2df15,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,seller_state,str,0,0.0,23,SP,1849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,seller_zip_code_prefix,int64,0,0.0,2246,14940,49,32291.059451,32713.45383,7093.5,14940.0,64552.5,1001.0,99730.0,0.916092,-0.858264

In [7]:
order_items['order_item_id'].value_counts()

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [8]:
%run ../src/preprocessing_utils.py

2026-08-24 19:16:42,013 [INFO] Carregando customers de ..\data\raw\olist_customers_dataset.csv
2026-08-24 19:16:42,282 [INFO] Carregando orders de ..\data\raw\olist_orders_dataset.csv
2026-08-24 19:16:42,755 [INFO] Carregando order_items de ..\data\raw\olist_order_items_dataset.csv
2026-08-24 19:16:43,067 [INFO] Carregando payments de ..\data\raw\olist_order_payments_dataset.csv
2026-08-24 19:16:43,213 [INFO] Carregando reviews de ..\data\raw\olist_order_reviews_dataset.csv
2026-08-24 19:16:43,699 [INFO] Carregando products de ..\data\raw\olist_products_dataset.csv
2026-08-24 19:16:43,776 [INFO] Carregando sellers de ..\data\raw\olist_sellers_dataset.csv
2026-08-24 19:16:43,783 [INFO] Carregando geolocation de ..\data\raw\olist_geolocation_dataset.csv
2026-08-24 19:16:44,904 [INFO] Carregando category_translation de ..\data\raw\product_category_name_translation.csv
2026-08-24 19:16:45,366 [INFO] orders + customers -> (99441, 12)
2026-08-24 19:16:45,723 [INFO] + order_items -> (112650, 18)
2026-08-24 19:16:45,916 [INFO] + products (traduzido) -> (112650, 27)
2026-08-24 19:16:45,976 [INFO] + sellers -> (112650, 30)
2026-08-24 19:17:34,160 [INFO] + payments (agregado) -> (112650, 34)
2026-08-24 19:17:34,631 [INFO] + reviews (deduplicado) -> (112650, 40)
2026-08-24 19:17:34,631 [INFO] Dataset final unificado: (112650, 40)
2026-08-24 19:17:35,482 [INFO] Salvo em ..\data\interim\olist_merged.parquet (112650 linhas, 40 colunas)
2026-08-24 19:17:36,238 [INFO] Duplicatas exatas removidas: 0
2026-08-24 19:17:36,241 [INFO] Colunas com valores nulos:
review_comment_title             99235
review_comment_message           65252
order_delivered_customer_date     2454
product_category_name_english     1627
product_name_lenght               1603
product_category_name             1603
product_description_lenght        1603
product_photos_qty                1603
order_delivered_carrier_date      1194
review_id                          942
review_answer_timestamp            942
review_score                       942
review_creation_date               942
product_weight_g                    18
product_width_cm                    18
product_length_cm                   18
product_height_cm                   18
order_approved_at                   15
payment_installments_max             3
payment_value_total                  3
payment_type_mode                    3
n_payment_methods                    3
dtype: int64
2026-08-24 19:17:36,693 [INFO] Salvo em ..\data\processed\olist_processed.parquet (112650 linhas, 40 colunas)

In [10]:
df_merged = pd.read_parquet("../data/interim/olist_merged.parquet")
df_merged.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_value_total,payment_installments_max,payment_type_mode,n_payment_methods,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,38.71,1.0,voucher,2.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,141.46,1.0,boleto,1.0,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,179.12,3.0,credit_card,1.0,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,...,72.20,1.0,credit_card,1.0,359d03e676b3c069f62cadba8dd3f6e8,5.0,NaN,O produto foi exatamente o que eu esperava e e...,2017-12-03 00:00:00,2017-12-05 19:21:58
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,28.62,1.0,credit_card,1.0,e50934924e227544ba8246aeb3770dd4,5.0,NaN,NaN,2018-02-17 00:00:00,2018-02-18 13:02:51

In [14]:
dataframe_summary(df_merged)

,dtype,total_null,percent_null,unique,top,freq,mean,std,25%,50%,75%,min,max,skew,kurtosis
feature,,,,,,,,,,,,,,,
customer_city,str,0,0.00,4110,sao paulo,17808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,str,0,0.00,98666,fc3d1daec319d62d49bfb5e1f83123e9,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_state,str,0,0.00,27,SP,47449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_unique_id,str,0,0.00,95420,c8460e4251689ba205045f3ea17884a1,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_zip_code_prefix,int64,0,0.00,14976,22790,154,35119.309090,29866.120801,11310.00,24340.00,59028.75,1003.00,99990.00,0.780165,-0.792801
freight_value,float64,0,0.00,6999,15.1,3707,19.990320,15.806405,13.08,16.26,21.15,0.00,409.68,5.639870,59.788253
n_payment_methods,float64,3,0.00,2,1.0,110159,1.022087,0.146966,1.00,1.00,1.00,1.00,2.00,6.503833,40.300553
order_approved_at,str,15,0.01,90174,2018-02-24 03:20:27,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_delivered_carrier_date,str,1194,1.06,81017,2018-05-09 15:48:00,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_delivered_customer_date,str,2454,2.18,95664,2017-07-31 18:03:02,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_estimated_delivery_date,str,0,0.00,450,2017-12-20 00:00:00,604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_id,str,0,0.00,98666,8272b63d03f5f79c56e9e4120aec44ef,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_item_id,int64,0,0.00,21,1,98666,1.197834,0.705124,1.00,1.00,1.00,1.00,21.00,7.580356,103.857361
order_purchase_timestamp,str,0,0.00,98112,2017-07-16 18:19:25,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_status,str,0,0.00,7,delivered,110197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_installments_max,float64,3,0.00,24,1.0,53868,3.018385,2.802552,1.00,2.00,4.00,0.00,24.00,1.567871,2.337458
payment_type_mode,str,3,0.00,4,credit_card,86017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_value_total,float64,3,0.00,27845,77.57,254,180.281186,272.849042,65.67,114.44,195.39,9.59,13664.08,13.877738,489.284858
price,float64,0,0.00,5968,59.9,2481,120.653739,183.633928,39.90,74.99,134.90,0.85,6735.00,7.923208,120.828298
product_category_name,str,1603,1.42,73,cama_mesa_banho,11115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_category_name_english,str,1627,1.44,71,bed_bath_table,11115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_description_lenght,float64,1603,1.42,2960,341.0,690,787.867029,652.135608,348.00,603.00,987.00,4.00,3992.00,2.005550,4.901255
product_height_cm,float64,18,0.02,102,10.0,9826,16.593766,13.443483,8.00,13.00,20.00,2.00,105.00,2.253810,7.384688
product_id,str,0,0.00,32951,aca2eb7d00ea1a7b8ebd4e68314663af,527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_length_cm,float64,18,0.02,99,16.0,17603,30.153669,16.153449,18.00,25.00,38.00,7.00,105.00,1.761463,3.745488
product_name_lenght,float64,1603,1.42,66,59.0,8322,48.775978,10.025581,42.00,52.00,57.00,5.00,76.00,-0.907144,0.156610
product_photos_qty,float64,1603,1.42,19,1.0,56028,2.209713,1.721438,1.00,1.00,3.00,1.00,20.00,1.907908,4.834775
product_weight_g,float64,18,0.02,2204,200.0,6778,2093.672047,3751.596884,300.00,700.00,1800.00,0.00,40425.00,3.598715,16.264762
product_width_cm,float64,18,0.02,95,20.0,12095,22.996546,11.707268,15.00,20.00,30.00,6.00,118.00,1.726601,4.686966
review_answer_timestamp,str,942,0.84,97234,2017-07-30 14:19:07,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_comment_message,str,65252,57.92,35593,Muito bom,254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_comment_title,str,99235,88.09,4495,Recomendo,471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_creation_date,str,942,0.84,633,2017-12-19 00:00:00,512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_id,str,942,0.84,97396,e8236fe7b6e1bdd513a500de361e2b87,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_score,float64,942,0.84,5,5.0,63157,4.032854,1.387526,4.00,5.00,5.00,1.00,5.00,-1.273456,0.207653
seller_city,str,0,0.00,611,sao paulo,27983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_id,str,0,0.00,3095,6560211a19b47992c3666cc44a7e94c0,2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_state,str,0,0.00,23,SP,80342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_zip_code_prefix,int64,0,0.00,2246,14940,7750,24439.170431,27596.030909,6429.00,13568.00,27930.00,1001.00,99730.00,1.555411,0.932614
shipping_limit_date,str,0,0.00,93318,2018-03-01 02:50:48,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_processed = pd.read_parquet("../data/processed/olist_processed.parquet")
df_processed.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_value_total,payment_installments_max,payment_type_mode,n_payment_methods,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,38.71,1.0,voucher,2.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,141.46,1.0,boleto,1.0,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08,2018-08-08 18:37:50
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,179.12,3.0,credit_card,1.0,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18,2018-08-22 19:07:58
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,72.20,1.0,credit_card,1.0,359d03e676b3c069f62cadba8dd3f6e8,5.0,NaN,O produto foi exatamente o que eu esperava e e...,2017-12-03,2017-12-05 19:21:58
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,28.62,1.0,credit_card,1.0,e50934924e227544ba8246aeb3770dd4,5.0,NaN,NaN,2018-02-17,2018-02-18 13:02:51

In [16]:
dataframe_summary(df_processed)

,dtype,total_null,percent_null,unique,top,freq,mean,std,25%,50%,75%,min,max,skew,kurtosis
feature,,,,,,,,,,,,,,,
customer_city,str,0,0.00,4110,sao paulo,17808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,str,0,0.00,98666,fc3d1daec319d62d49bfb5e1f83123e9,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_state,str,0,0.00,27,SP,47449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_unique_id,str,0,0.00,95420,c8460e4251689ba205045f3ea17884a1,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_zip_code_prefix,int64,0,0.00,14976,22790,154,35119.309090,29866.120801,11310.00,24340.00,59028.75,1003,99990,0.780165,-0.792801
freight_value,float64,0,0.00,6999,15.1,3707,19.990320,15.806405,13.08,16.26,21.15,0.0,409.68,5.639870,59.788253
n_payment_methods,float64,3,0.00,2,1.0,110159,1.022087,0.146966,1.00,1.00,1.00,1.0,2.0,6.503833,40.300553
order_approved_at,datetime64[us],15,0.01,90174,2018-02-24 03:20:27,23,NaN,NaN,NaN,NaN,NaN,2016-09-15 12:16:38,2018-09-03 17:40:06,NaN,NaN
order_delivered_carrier_date,datetime64[us],1194,1.06,81017,2018-05-09 15:48:00,48,NaN,NaN,NaN,NaN,NaN,2016-10-08 10:34:01,2018-09-11 19:48:28,NaN,NaN
order_delivered_customer_date,datetime64[us],2454,2.18,95664,2017-07-31 18:03:02,21,NaN,NaN,NaN,NaN,NaN,2016-10-11 13:46:32,2018-10-17 13:22:46,NaN,NaN
order_estimated_delivery_date,datetime64[us],0,0.00,450,2017-12-20 00:00:00,604,NaN,NaN,NaN,NaN,NaN,2016-10-04 00:00:00,2018-10-25 00:00:00,NaN,NaN
order_id,str,0,0.00,98666,8272b63d03f5f79c56e9e4120aec44ef,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_item_id,int64,0,0.00,21,1,98666,1.197834,0.705124,1.00,1.00,1.00,1,21,7.580356,103.857361
order_purchase_timestamp,datetime64[us],0,0.00,98112,2017-07-16 18:19:25,21,NaN,NaN,NaN,NaN,NaN,2016-09-04 21:15:19,2018-09-03 09:06:57,NaN,NaN
order_status,str,0,0.00,7,delivered,110197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_installments_max,float64,3,0.00,24,1.0,53868,3.018385,2.802552,1.00,2.00,4.00,0.0,24.0,1.567871,2.337458
payment_type_mode,str,3,0.00,4,credit_card,86017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_value_total,float64,3,0.00,27845,77.57,254,180.281186,272.849042,65.67,114.44,195.39,9.59,13664.08,13.877738,489.284858
price,float64,0,0.00,5968,59.9,2481,120.653739,183.633928,39.90,74.99,134.90,0.85,6735.0,7.923208,120.828298
product_category_name,str,1603,1.42,73,cama_mesa_banho,11115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_category_name_english,str,1627,1.44,71,bed_bath_table,11115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_description_lenght,float64,1603,1.42,2960,341.0,690,787.867029,652.135608,348.00,603.00,987.00,4.0,3992.0,2.005550,4.901255
product_height_cm,float64,18,0.02,102,10.0,9826,16.593766,13.443483,8.00,13.00,20.00,2.0,105.0,2.253810,7.384688
product_id,str,0,0.00,32951,aca2eb7d00ea1a7b8ebd4e68314663af,527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_length_cm,float64,18,0.02,99,16.0,17603,30.153669,16.153449,18.00,25.00,38.00,7.0,105.0,1.761463,3.745488
product_name_lenght,float64,1603,1.42,66,59.0,8322,48.775978,10.025581,42.00,52.00,57.00,5.0,76.0,-0.907144,0.156610
product_photos_qty,float64,1603,1.42,19,1.0,56028,2.209713,1.721438,1.00,1.00,3.00,1.0,20.0,1.907908,4.834775
product_weight_g,float64,18,0.02,2204,200.0,6778,2093.672047,3751.596884,300.00,700.00,1800.00,0.0,40425.0,3.598715,16.264762
product_width_cm,float64,18,0.02,95,20.0,12095,22.996546,11.707268,15.00,20.00,30.00,6.0,118.0,1.726601,4.686966
review_answer_timestamp,datetime64[us],942,0.84,97234,2017-07-30 14:19:07,21,NaN,NaN,NaN,NaN,NaN,2016-10-07 18:32:28,2018-10-29 12:27:35,NaN,NaN
review_comment_message,str,65252,57.92,35593,Muito bom,254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_comment_title,str,99235,88.09,4495,Recomendo,471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_creation_date,datetime64[us],942,0.84,633,2017-12-19 00:00:00,512,NaN,NaN,NaN,NaN,NaN,2016-10-06 00:00:00,2018-08-31 00:00:00,NaN,NaN
review_id,str,942,0.84,97396,e8236fe7b6e1bdd513a500de361e2b87,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_score,float64,942,0.84,5,5.0,63157,4.032854,1.387526,4.00,5.00,5.00,1.0,5.0,-1.273456,0.207653
seller_city,str,0,0.00,611,sao paulo,27983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_id,str,0,0.00,3095,6560211a19b47992c3666cc44a7e94c0,2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_state,str,0,0.00,23,SP,80342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_zip_code_prefix,int64,0,0.00,2246,14940,7750,24439.170431,27596.030909,6429.00,13568.00,27930.00,1001,99730,1.555411,0.932614
shipping_limit_date,str,0,0.00,93318,2018-03-01 02:50:48,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_processed.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'product_category_name_english', 'seller_zip_code_prefix',
       'seller_city', 'seller_state', 'payment_value_total',
       'payment_installments_max', 'payment_type_mode', 'n_payment_methods',
       'review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')